# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4bb066f9b771172a826b27c3e2e4b66f563ac045eec703435462b617c3ef6f20c1b891f00c8cf17b91b65cfebbf6a3ae92bd5974d1d698796bd8ca5ab323807

test:
  secret_key_base: f79102eb82a42c1160a7c5d4cf2f85340adabe547aecb2acfb5a6c397b7ecb7c8bbc82b21dcfa04a9baaf4be7b06eecea0e9bbc08fa9d2ddc641c527fdf7b243

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
